---
- name: Check if wpcli is already installed.
  ansible.builtin.stat:
    path: "{{ wpcli_path }}"
  register: wpcli_bin

- name: Download and install wpcli.
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
    dest: "{{ wpcli_path }}"
    mode: "0755"
  when: not wpcli_bin.stat.exists

- name: Update wpcli to the latest version.
  ansible.builtin.command: wp cli update
  register: result
  changed_when: "'Success: Updated' in result.stdout"
  when: wpcli_bin.stat.exists

- name: Create wpcli config directory.
  ansible.builtin.file:
    path: "{{ user_home_path }}/.wp-cli"
    mode: "0755"
    state: directory

- name: Generate wpcli configuration.
  ansible.builtin.template:
    src: wpcli.yml.j2
    dest: "{{ user_home_path }}/.wp-cli/config.yml"
    mode: "0644"

- name: Get wpcli version.
  ansible.builtin.command: wp --version
  changed_when: false
  register: test_version

- name: Run tests.
  ansible.builtin.assert:
    that:
      - test_version is search("WP-CLI")
