---
nginx_ssl_key: null
nginx_ssl_cert: null
nginx_real_ip_from: [ ]
nginx_proxies: [ ]
#  - container: test-1
#    ports:
#      - port: 22
#        host_port: 2221
#    hosts:
#      - test-1.127.0.0.1.nip.io
