---
wp_url: null
wp_user: null
wp_password: null

wp_title: "{{ ansible_hostname }}"
wp_email: "{{ wp_user }}@sitepilot.io"
wp_path: "{{ user_files_path }}"
wp_plugins: [ ]

wp_db_host: "localhost"
wp_db_name: "{{ database_name }}"
wp_db_user: "{{ database_user }}"
wp_db_password: "{{ database_password }}"
