---
- name: Add litespeed repository key.
  ansible.builtin.apt_key:
    id: "0x011AA62DEDA1F085"
    keyserver: keyserver.ubuntu.com
    keyring: /etc/apt/trusted.gpg.d/litespeed.gpg

- name: Add litespeed repository.
  ansible.builtin.apt_repository:
    repo: "deb https://rpms.litespeedtech.com/debian/ {{ ansible_distribution_release }} main"
    filename: litespeed
    update_cache: true

- name: Ensure litespeed is installed.
  ansible.builtin.apt:
    name: openlitespeed
    state: present
    cache_valid_time: 3600
  notify: reload litespeed

- name: Generate litespeed configuration.
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
    mode: "0644"
    owner: lsadm
    group: nogroup
  notify: reload litespeed
  loop:
    - template: httpd_config.j2
      destination: "/usr/local/lsws/conf/httpd_config.conf"
    - template: vhost.j2
      destination: "/usr/local/lsws/conf/vhosts/app.conf"
