#!/bin/bash

set -e
set -u
set -o pipefail

# ---------------------------------------------------------- #
# Configuration
# ---------------------------------------------------------- #
CONTAINER=test-container
SSH_PORT=4022
HTTP_PORT=4080
LSADM_PORT=4070

# ---------------------------------------------------------- #
# Defaults
# ---------------------------------------------------------- #
COLOR_RED='\033[0;31m'
COLOR_NONE='\033[0m'

# ---------------------------------------------------------- #
# Functions
# ---------------------------------------------------------- #
function log {
  DATETIME=$(date '+%Y/%m/%d %H:%M:%S')
  echo -e "[STACK][$DATETIME] $1"
}

function error {
  log "${COLOR_RED}$1${COLOR_NONE}"
  exit 1
}

function init {
  lxc launch ubuntu:jammy $CONTAINER || return 1

  lxc config device add $CONTAINER ssh proxy listen=tcp:0.0.0.0:$SSH_PORT connect=tcp:127.0.0.1:22 || return 1
  lxc config device add $CONTAINER http proxy listen=tcp:0.0.0.0:$HTTP_PORT connect=tcp:127.0.0.1:80 || return 1
  lxc config device add $CONTAINER lsadm proxy listen=tcp:0.0.0.0:$LSADM_PORT connect=tcp:127.0.0.1:7080 || return 1

  sleep 5

  chmod -R 600 ./ssh/id_ed25519

  lxc file push ./ssh/authorized_keys $CONTAINER/root/.ssh/authorized_keys

  lxc exec $CONTAINER -- chown root:root /root/.ssh/authorized_keys || return 1
}

function provision {
  ansible-playbook playbooks/provision.yml -e host=test-container "${@}" || return 1
}

function backup {
  ansible-playbook playbooks/backup.yml -e host=test-container "${@}" || return 1
}

function wordpress {
  ansible-playbook playbooks/wordpress.yml -e host=test-container "${@}" || return 1
}

function shell {
  lxc exec $CONTAINER bash || return 1
}

function wp-pull {
  ansible-playbook playbooks/wordpress/pull.yml -e host=test-container "${@}" || return 1
}

function snapshot {
  lxc snapshot $CONTAINER || return 1
}

function restore {
  lxc restore $CONTAINER $1 || return 1
}

function destroy {
  lxc delete $CONTAINER -f || return 1
}

# ---------------------------------------------------------- #
# Commands
# ---------------------------------------------------------- #
case "$1" in
init)
  init || error "Failed to initialize the container."
  ;;
provision)
  provision "${@:2}" || error "Failed to provision the container."
  ;;
backup)
  backup "${@:2}" || error "Failed to run backup commands in the container."
  ;;
wordpress)
  wordpress "${@:2}" || error "Failed to run WordPress commands in the container."
  ;;
shell)
  shell || error "Failed to start a shell."
  ;;
wp-pull)
  wp-pull "${@:2}" || error "Failed to pull WordPress to the container."
  ;;
snapshot)
  snapshot || error "Failed to create a snapshot."
  ;;
restore)
  restore $2 || error "Failed to restore a snapshot."
  ;;
destroy)
  destroy || error "Failed to destroy test container."
  ;;
*)
  log "No command specified."
  ;;
esac
