---
- ansible.builtin.assert:
    that:
      - user_name | length > 0
      - user_password | length > 0

- name: Ensure user group exists.
  ansible.builtin.group:
    name: "{{ user_name }}"
    state: present
    gid: 1001

- name: Ensure user exists.
  ansible.builtin.user:
    name: "{{ user_name }}"
    group: "{{ user_name }}"
    password: "{{ user_password }}"
    groups: "{{ user_groups }}"
    shell: "{{ user_shell }}"
    create_home: true
    home: /app
    uid: 1001

- name: Add authorized keys.
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    state: "present"
    key: "{{ user_authorized_keys | join('\n') }}"
    exclusive: true

- name: Create logs directory.
  ansible.builtin.file:
    path: /app/logs
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
