---
- name: Import install tasks.
  ansible.builtin.import_tasks: install.yml
  when: valkey_enabled

- name: Import uninstall tasks.
  ansible.builtin.import_tasks: uninstall.yml
  when: not valkey_enabled
