---
- name: Import install tasks.
  ansible.builtin.import_tasks: install.yml
  when: mariadb_enabled

- name: Import uninstall tasks.
  ansible.builtin.import_tasks: uninstall.yml
  when: not mariadb_enabled
