---
- name: Ensure restic is installed.
  ansible.builtin.apt:
    name: restic
    state: present
    cache_valid_time: 3600
  tags: always

- name: Ensure private directory exists;
  ansible.builtin.file:
    path: /app/private
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
  tags: always

- ansible.builtin.import_tasks: create.yml
  tags:
    - never
    - create

- ansible.builtin.import_tasks: restore.yml
  tags:
    - never
    - restore

- ansible.builtin.import_tasks: destroy.yml
  tags:
    - never
    - destroy
