---
- ansible.builtin.assert:
    that:
      - "'mysql' in stack"

- name: Check installed version.
  ansible.builtin.stat:
    path: "/opt/phpmyadmin/.version-{{ phpmyadmin_version }}"
  register: version_check

- name: Cleanup old installation files.
  ansible.builtin.file:
    state: absent
    path: "/opt/phpmyadmin"
  when: not version_check.stat.exists

- name: Download and unzip source.
  ansible.builtin.unarchive:
    src: "https://files.phpmyadmin.net/phpMyAdmin/{{ phpmyadmin_version }}/phpMyAdmin-{{ phpmyadmin_version }}-all-languages.zip"
    dest: "/opt"
    remote_src: true
  when: not version_check.stat.exists

- name: Rename source folder.
  ansible.builtin.command: "mv /opt/phpMyAdmin-{{ phpmyadmin_version }}-all-languages /opt/phpmyadmin"
  when: not version_check.stat.exists
  changed_when: false

- name: Create version file.
  ansible.builtin.copy:
    content: "{{ phpmyadmin_version }}"
    dest: "/opt/phpmyadmin/.version-{{ phpmyadmin_version }}"
    mode: "0644"
  when: not version_check.stat.exists

- name: Check blowfish file.
  ansible.builtin.stat:
    path: "/opt/phpmyadmin/blowfish.inc.php"
  register: blowfish_check

- name: Generate blowfish secret.
  ansible.builtin.template:
    src: blowfish.j2
    dest: "/opt/phpmyadmin/blowfish.inc.php"
    mode: "0644"
  when: not blowfish_check.stat.exists

- name: Update permissions.
  ansible.builtin.file:
    state: "directory"
    path: "/opt/phpmyadmin/tmp"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"

- name: Generate configuartion.
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - src: config.j2
      dest: "/opt/phpmyadmin/config.inc.php"
