---
- name: Validate variables.
  ansible.builtin.assert:
    that:
      - node_version in node_versions

- name: Add node repository key.
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    keyring: /etc/apt/trusted.gpg.d/nodejs.gpg

- name: Add node repository.
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x nodistro main"
    filename: node
    update_cache: true

- name: Ensure node is installed.
  ansible.builtin.apt:
    name: "nodejs={{ node_version }}*"
    state: present
    allow_downgrade: true
