---
- name: Import install tasks.
  ansible.builtin.import_tasks: install.yml
  when: node_version

- name: Import uninstall tasks.
  ansible.builtin.import_tasks: uninstall.yml
  when: not node_version
