---
- name: Create public directory.
  ansible.builtin.file:
    path: /app/public
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"

- name: Ensure php-fpm is installed.
  ansible.builtin.apt:
    name: php{{ php_version }}-fpm
    state: present
    cache_valid_time: 3600
  notify: restart php-fpm

- name: Generate php configuration.
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
    mode: "0644"
  notify: restart php-fpm
  loop:
    - template: pool.j2
      destination: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    - template: php.j2
      destination: "/etc/php/{{ php_version }}/fpm/conf.d/90-app.ini"
