---
- name: Ensure nginx is installed.
  ansible.builtin.apt:
    name:
      - nginx
      - libnginx-mod-stream
    state: present
    cache_valid_time: 3600
  notify: reload nginx

- name: Generate nginx certificate.
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
    mode: "0644"
  loop:
    - template: ssl.key.j2
      destination: /etc/nginx/ssl.key
    - template: ssl.cert.j2
      destination: /etc/nginx/ssl.cert
  when:
    - nginx_ssl_key
    - nginx_ssl_cert
  notify: reload nginx

- name: Generate nginx configuration.
  ansible.builtin.template:
    src: "{{ item.template }}"
    dest: "{{ item.destination }}"
    mode: "0644"
  loop:
    - template: nginx.conf.j2
      destination: /etc/nginx/nginx.conf
    - template: errors.conf.j2
      destination: /etc/nginx/snippets/errors.conf
    - template: proxy.conf.j2
      destination: /etc/nginx/snippets/proxy.conf
    - template: errors/404.html.j2
      destination: /usr/share/nginx/html/custom_404.html
    - template: errors/413.html.j2
      destination: /usr/share/nginx/html/custom_413.html
    - template: errors/502.html.j2
      destination: /usr/share/nginx/html/custom_502.html
    - template: errors/503.html.j2
      destination: /usr/share/nginx/html/custom_503.html
    - template: errors/504.html.j2
      destination: /usr/share/nginx/html/custom_504.html
  notify: reload nginx
  tags: configure-proxy
