---
user_name: null
user_group: "{{ user_name }}"
user_groups: [ ]
user_password: !
user_auth_keys: [ ]
user_home_path: "/home/container"
user_logs_path: "{{ user_home_path }}/logs"
user_files_path: "{{ user_home_path }}/files"

server_type: null
server_public_dir: /
server_public_path: "{{ user_files_path }}{{ server_public_dir }}"
server_upload_limit: "{{ php_upload_limit | default('100M') }}"
server_error_log: "{{ user_logs_path }}/error.log"
server_access_log: "{{ user_logs_path }}/access.log"

database_type: null
database_name: "{{ user_name }}"
database_user: "{{ user_name }}"
database_password: null

cache_type: null
