---
name: run-tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    env:
      ANSIBLE_INVENTORY: ./tests/hosts
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install ansible collections
        run: ansible-galaxy install -r requirements.yml --force

      - name: Install pip packages
        run: pip3 install -r ./requirements.txt

      - name: Lint ansible files
        run: ansible-lint ./roles

      - uses: canonical/setup-lxd@main
        with:
          channel: 5.21/stable

      - name: Create test containers
        run: |
          lxc launch ubuntu:24.04 test-1

      - name: Setup container SSH keys
        run: |
          ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
          lxc file push ./ssh/test.pub test-1/root/.ssh/authorized_keys
          lxc exec test-1 chown root:root /root/.ssh/authorized_keys

      - name: Test server playbook
        run: ansible-playbook server.yml

      - name: Test container playbook
        run: ansible-playbook container.yml
