---
name: run-tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    env:
      ANSIBLE_INVENTORY: ./tests/hosts
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install ansible collections
        run: ansible-galaxy install -r requirements.yml --force

      - name: Install pip packages
        run: pip3 install -r ./requirements.txt

      - name: Lint ansible files
        run: ansible-lint ./roles

      - uses: canonical/setup-lxd@main
        with:
          channel: 5.21/stable

      - name: Create test containers
        run: |
          lxc launch ubuntu:24.04 test-d1x

      - name: Setup container SSH keys
        run: |
          ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
          lxc file push ~/.ssh/id_rsa.pub test-d1x/root/.ssh/authorized_keys
          lxc config device add test-d1x ssh proxy listen=tcp:0.0.0.0:2221 connect=tcp:127.0.0.1:22

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Test container provision roles
        run: ansible-playbook container.yml
