---
name: run-tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install pip packages
        run: pip3 install -r ./requirements.txt

      - name: Install collections
        run: ansible-galaxy install -r ./requirements.yml

      - name: Lint Ansible files
        run: ansible-lint ./roles

      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: latest/stable

      - name: Initialize test container
        run: ./container init

      - name: Test provision playbook
        run: ./container provision

      - name: Test backup playbook
        run: |
          ./container backup -t create
          ./container backup -t restore
          ./container backup -t destroy
